config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'

  resources :schools do
  	resources :classrooms
  end
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	validates_presence_of :name
	belongs_to :school

	def class_name
		"#{name} classroom"
	end

	def class_size
		if (size >= 100)
			"Large"
		elsif (size >= 50)
			"Descent"
		else
			"Small"
		end
	end

end

app/models/school.rb
class School < ActiveRecord::Base
	validates_presence_of :name, :mascot, :year
	has_many :classrooms

	def name_mascot
		"#{name} home of the #{mascot}"
	end

	def school_age
		if (year >= 2000)
			"New"
		elsif (year >= 1800)
			"Pretty old"
		else
			"Way old"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :school
  before_action :classroom, except: [:index, :new, :create]
  def index
  	@classrooms = @school.classrooms.all
  end

  def show
  end

  def new
  	@classroom = @school.classrooms.new
  end

  def create
  	@classroom = @school.classrooms.new(classroom_params)
  	if @classroom.save
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @classroom.update(classroom_params)
  		flash[:success] = 'Class has been updated'
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :edit
  	end
  end

  def destroy
  	@classroom.destroy
  	redirect_to school_classrooms_path
  end

  private
  	def classroom
  		@classroom = @school.classrooms.find(params[:id])
  	end

  	def school
			@school = School.find(params[:school_id])
		end

  	def classroom_params
  		params.require(:classroom).permit(:name, :size)
  	end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :school, except: [:index, :new, :create]

  def index
  	@schools = School.all
  end

  def show
  end

  def new
  	@school = School.new
  end

  def create
  	@school = School.new(school_params)
  	if @school.save
  		redirect_to school_path(@school)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @school.update(school_params)
  		flash[:success] = 'The school has been updated successfully!'
  		redirect_to school_path(@school)
  	else
  		render :edit
  	end
  end

  def destroy
  	@school.destroy
  	redirect_to schools_path
	end

	private
		def school
			@school = School.find(params[:id])
		end

		def school_params
			params.require(:school).permit(:name, :year, :mascot)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for [@school, @classroom] do |f| %>

	<div class="row">
		<div class="input-field col s6 offset-s3">
			<%= f.label :name, class: 'white-text' %>
			<%= f.text_field :name, class: 'brown-text text-darken-4' %>
		</div>
	</div>

	<div class="row">
		<div class="input-field col s6 offset-s3">
			<%= f.label :size, class: 'white-text' %>
			<%= f.number_field :size, class: 'brown-text text-darken-4' %>
		</div>
	</div>

	<%= f.submit nil, class: "submit-classroom-btn btn" %>

<% end %>

app/views/classrooms/edit.html.erb
<h1 class='white-text'>Editing classroom info</h1>

<%= render('form') %>

app/views/classrooms/index.html.erb
<h1 class='classroom-header white-text'>Classrooms</h1>

<% if @classrooms.any? %>
  <div class='row'>
    <% @classrooms.each do |classroom| %>
      <div class="col s12 m6">
       <div class="card grey lighten-2">
         <div class="card-content brown-text">
           <span class="card-title classname"><%= @school.classrooms.name %></span>
         </div>
         <div class="card-action">
           <%= link_to 'More info', school_classroom_path(@school, classroom), class: 'btn' %>
         </div>
       </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 class='no-class-msg white-text'>There Is No classroom, Go make one!</h3>
<% end %>

<%= link_to 'New Class', new_school_classroom_path(@school), class: 'new-classroom btn' %>

app/views/classrooms/new.html.erb
<h1 class='white-text'>Create A Class</h1>


<%= render('form') %>

app/views/classrooms/show.html.erb
<h1 class='classroom-header white-text'>Showing <%= @classroom.name %> size of <%= @classroom.size %> </h1>

<%= link_to 'Edit', edit_school_classroom_path(@school, @classroom), class: 'edit-class btn' %>
<%= link_to 'Delete', school_classroom_path(@school, @classroom), method: :delete, class: 'class-delete btn' %>
<%= link_to 'Back', school_classrooms_path(@school), class: 'class-back btn' %>

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="center brand-logo">Pirate School District</a>
      <ul class="left hide-on-med-and-down">
        <li><%= link_to 'All Schools', schools_path, class: 'school-back active' %></li>
      </ul>
	      <form>
	        <div class="right input-field">
	         <label for="search"><i class="material-icons">search</i></label>
	         <input id="search" type="search" required>
	         <i class="material-icons">close</i>
	        </div>
	      </form>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='center-align'>
<head>
  <title>SchoolRails</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= render('layouts/navbar') %>
<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
	<div class="row">
		<div class="input-field col s6 offset-s3">
			<%= f.label :name, class: 'white-text' %>
			<%= f.text_field :name, class: 'brown-text text-darken-4' %>
		</div>
	</div>

	<div class="row">
		<div class="input-field col s6 offset-s3">
			<%= f.label :mascot, class: 'white-text' %>
			<%= f.text_field :mascot, class: 'brown-text text-darken-4' %>
		</div>
	</div>

	<div class="row">
		<div class="input-field col s6 offset-s3">
			<%= f.label :year, class: 'white-text' %>
			<%= f.number_field :year, class: 'brown-text text-darken-4' %>
		</div>
	</div>

	<%= f.submit nil, class: "submit-school-btn btn" %>

<% end %>

app/views/schools/edit.html.erb
<h1 class='white-text'>Editing School</h1>


<%= render('form') %>

app/views/schools/index.html.erb
<h1 class='school-header white-text'>Schools</h1>


<% if @schools.any? %>
  <div class='row'>
    <% @schools.each do |school| %>
      <div class="col s12 m6">
       <div class="card grey lighten-2">
         <div class="card-content white-text">
           <span class="card-title brown-text"><%= school.name %></span>
         </div>
         <div class="card-action">
           <%= link_to 'More info', school_path(school), class: 'btn' %>
           <%= link_to 'Edit', edit_school_path(school), class: 'school-edit btn' %>
           <!-- TODO Find out why the delete makes the id a . instead of a / -->
           <%= link_to 'Delete', schools_path(@school), method: :delete, class: 'delete-school-btn btn' %>
         </div>
       </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 class='no-school-msg white-text'>There Is No School, Go make one!</h3>
<% end %>

<%= link_to 'New School', new_school_path, class: 'new-school-btn btn' %>

app/views/schools/new.html.erb
<h1 class='white-text'>Create A New School</h1>


<%= render('form') %>

app/views/schools/show.html.erb
<h1 class='show-header white-text'>Showing <%= @school.name %> home of the <%= @school.mascot %> </h1>

<h3 class='year-header white-text'>Year Built: <%= @school.year %></h3>

<%= link_to 'Back to school', schools_path, class: 'school-back btn' %>
<%= link_to 'Show classes', school_classrooms_path(@school), class: 'index-classroom-btn btn' %>